---
- name: Backup QCOW2 File
  hosts: IOT
  vars:
    qcow_dir: "{{ semaphore_qcow_dir }}"
    qcow_file: "{{ qcow_dir }}/Aapanel.qcow2"
    zip_file: "{{ qcow_dir }}/aapanel.qcow2.zip"
    vm_name: "{{ semaphore_vm_name | default('Panel') }}"

  tasks:
    - name: Ensure ZIP directory exists
      file:
        path: "{{ qcow_dir }}"
        state: directory

    - name: Get VM info
      community.libvirt.virt:
        name: "{{ vm_name }}"
        command: info
      register: vm_info

    - name: Debug VM info
      ansible.builtin.debug:
        var: vm_info

    - name: Shutdown VM if running
      community.libvirt.virt:
        name: "{{ vm_name }}"
        state: shutdown
      when: vm_info.status == "running"

    - name: Wait for VM to shut down
      community.libvirt.virt:
        name: "{{ vm_name }}"
        command: info
      register: shutdown_info
      until: shutdown_info.status == "shutdown"
      retries: 30
      delay: 5
      when: vm_info.status == "running"

    - name: Check if QCOW file exists
      ansible.builtin.stat:
        path: "{{ qcow_file }}"
      register: qcow_stat

    - name: Zip QCOW file
      ansible.builtin.archive:
        path: "{{ qcow_file }}"
        dest: "{{ zip_file }}"
        format: zip
      when: qcow_stat.stat.exists

    - name: Start VM
      community.libvirt.virt:
        name: "{{ vm_name }}"
        state: running

    - name: Wait for VM to start
      ansible.builtin.pause:
        seconds: 30

    - name: Print completion message
      ansible.builtin.debug:
        msg: "All operations completed successfully."