---
- name: Print OS information
  hosts: server
  gather_facts: yes

  tasks:
    - name: Display OS info
      ansible.builtin.debug:
        msg: "Operating System: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Display kernel version
      ansible.builtin.debug:
        msg: "Kernel version: {{ ansible_kernel }}"
